name: Create New File
on: [push]

jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create the file
        run: |

          echo hello>testhello.txt

          
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add new generated files"
